#!/usr/bin/env python3
"""DeepCode command-line entry point."""

import os
import subprocess
import sys
from pathlib import Path

# Console entrypoints generated by setuptools run from the environment's
# Scripts/bin directory, so imports like ``from core...`` are not guaranteed
# to see this source checkout even when the project is installed editable.
# Bootstrap the repository root ahead of everything else on sys.path.
PROJECT_ROOT = str(Path(__file__).resolve().parent)
if PROJECT_ROOT in sys.path:
    sys.path.remove(PROJECT_ROOT)
sys.path.insert(0, PROJECT_ROOT)

# The top-level package name ``cli`` is generic and is shadowed in some
# environments by a third-party ``cli`` distribution in site-packages. If one
# was already imported (cached in sys.modules) before us, ``cli.tui`` /
# ``cli.mcp_server`` would resolve into it and fail. Evict any ``cli`` that does
# not live under this checkout so our submodules import from the repo.
_cached_cli = sys.modules.get("cli")
if _cached_cli is not None and not (
    getattr(_cached_cli, "__file__", "") or ""
).startswith(PROJECT_ROOT):
    for _name in [n for n in list(sys.modules) if n == "cli" or n.startswith("cli.")]:
        del sys.modules[_name]

from core.platform_compat import (
    configure_utf8_stdio,
    subprocess_env,
)
from core.version import __version__

configure_utf8_stdio()


def print_banner():
    """Display startup banner."""
    width = 62
    lines = [
        "",
        " DeepCode — Open Agentic Coding",
        "",
        " Agentic code generation with multi-agent LLM systems",
        "",
    ]
    top = "╔" + "═" * width + "╗"
    bottom = "╚" + "═" * width + "╝"
    body = "\n".join("║" + ln.ljust(width)[:width] + "║" for ln in lines)
    print("\n" + top + "\n" + body + "\n" + bottom + "\n")


def launch_paper_test(paper_name: str, fast_mode: bool = False):
    """Launch paper testing mode"""
    try:
        print("\nLaunching Paper Test Mode")
        print(f"Paper: {paper_name}")
        print(f"Fast mode: {'enabled' if fast_mode else 'disabled'}")
        print("=" * 60)

        # Run the test setup
        setup_cmd = [sys.executable, "test_paper.py", paper_name]
        if fast_mode:
            setup_cmd.append("--fast")

        result = subprocess.run(setup_cmd, check=True, env=subprocess_env())

        if result.returncode == 0:
            print("\n[ok] Paper test setup completed successfully!")
            print("Files are ready in deepcode_lab/papers/")
            print("\nNext steps:")
            print(" 1. Install MCP dependencies: pip install -r requirements.txt")
            print(
                f" 2. Run full pipeline: python -m workflows.paper_test_engine --paper {paper_name}"
                + (" --fast" if fast_mode else "")
            )

    except subprocess.CalledProcessError as e:
        print(f"\n[x] Paper test setup failed: {e}")
        sys.exit(1)
    except Exception as e:  # noqa: BLE001 - top-level CLI error boundary
        print(f"\n[x] Unexpected error: {e}")
        sys.exit(1)


def _bootstrap_logging() -> None:
    """Install log sinks before anything can log.

    Without this, loguru keeps its built-in stderr sink at DEBUG level, so
    routine internals reach the terminal — most visibly the "config layer
    absent" line that ``load_config`` emits in any directory without a
    project-level ``deepcode_config.json`` (#167).

    Order matters and is the reason this is not simply
    ``setup_logging(load_config().logger)``: reading the config is itself
    one of the things that logs. So install a quiet default first, then
    re-apply only if the user asked for something else. ``DEEPCODE_LOG_LEVEL``
    wins over both and needs no config file, matching ``deepcode mcp``.

    Every subcommand below is dispatched from here, so this is the one place
    that has to remember — a per-entrypoint call would be the same four lines
    repeated ten times, and the next subcommand would forget them.
    """
    from core.config import LoggerConfig, load_config
    from core.observability import setup_logging

    override = os.environ.get("DEEPCODE_LOG_LEVEL")
    setup_logging(LoggerConfig(level=override or "INFO", transports=["console"]))
    if override:
        return

    try:
        configured = load_config().logger
    except Exception:
        # A broken or unreadable config is the subcommand's problem to report
        # properly; logging is already usable, so do not fail here.
        return
    if configured.level.upper() != "INFO":
        setup_logging(configured, force=True)


def main():
    """Main function"""
    _bootstrap_logging()

    # Parse command line arguments
    if len(sys.argv) > 1:
        if sys.argv[1] in {"--version", "-V"}:
            print(f"DeepCode {__version__}")
            return
        if sys.argv[1] == "test" and len(sys.argv) >= 3:
            # Paper testing mode: python deepcode.py test rice [--fast]
            paper_name = sys.argv[2]
            fast_mode = "--fast" in sys.argv or "-f" in sys.argv

            print_banner()
            launch_paper_test(paper_name, fast_mode)
            return
        elif sys.argv[1] == "init":
            # One-time setup: create the user-level config base (~/.deepcode) so
            # `deepcode` runs in any directory. Cross-platform (Win/mac/Linux).
            from cli.init_config import run as init_run

            raise SystemExit(init_run(sys.argv[2:]))
        elif sys.argv[1] == "mcp":
            # Bare/serve exposes DeepCode over stdio; list/add/remove manage the
            # generic MCP clients shared by CLI and Desktop.
            from cli.mcp_cli import run as mcp_main

            raise SystemExit(mcp_main(sys.argv[2:]))
        elif sys.argv[1] in {"skill", "skills"}:
            from cli.skill_cli import run as skill_run

            raise SystemExit(skill_run(sys.argv[2:]))
        elif sys.argv[1] in {"plugin", "plugins"}:
            from cli.plugin_cli import run as plugin_run

            raise SystemExit(plugin_run(sys.argv[2:]))
        elif sys.argv[1] in {"provider", "providers"}:
            from cli.provider_cli import run as provider_run

            raise SystemExit(provider_run(sys.argv[2:]))
        elif sys.argv[1] == "service":
            from cli.service_cli import run as service_run

            raise SystemExit(service_run(sys.argv[2:]))
        elif sys.argv[1] == "desktop":
            from cli.desktop_cli import run as desktop_run

            raise SystemExit(desktop_run(sys.argv[2:]))
        elif sys.argv[1] == "web":
            from cli.web_cli import run as web_run
            raise SystemExit(web_run(sys.argv[2:]))
        elif sys.argv[1] == "serve":
            from app_server.service import main as serve_main

            raise SystemExit(serve_main(sys.argv[2:]))
        elif sys.argv[1] in {"session", "sessions"}:
            from cli.session_cli import run as session_run

            raise SystemExit(session_run(sys.argv[2:]))
        elif sys.argv[1] in {"chat", "tui"}:
            from cli.tui.app import main as tui_main

            raise SystemExit(tui_main(sys.argv[2:]))
        elif sys.argv[1] == "exec":
            from cli.exec_cli import main as exec_main

            raise SystemExit(exec_main(sys.argv[2:]))
        elif sys.argv[1] == "loop":
            from cli.loop_cli import main as loop_main

            raise SystemExit(loop_main(sys.argv[2:]))
        elif sys.argv[1] == "schedule":
            from cli.schedule_cli import main as schedule_main

            raise SystemExit(schedule_main(sys.argv[2:]))
        elif sys.argv[1] in {"automation", "automations"}:
            from cli.automation_cli import run as automation_run

            raise SystemExit(automation_run(sys.argv[2:]))
        elif sys.argv[1] in ["--help", "-h", "help"]:
            print_banner()

            def row(cmd, desc):
                return f"   {cmd:<48}{desc}"

            print(
                "\n".join(
                    [
                        "",
                        "Usage:",
                        row("deepcode", "Open the terminal coding agent (TUI)"),
                        row("deepcode desktop", "Open the native desktop client"),
                        row("deepcode web", "Open the local browser client"),
                        row(
                            "deepcode init",
                            "Set up ~/.deepcode so deepcode runs anywhere",
                        ),
                        row("deepcode test <paper>", "Test paper reproduction"),
                        row("deepcode test <paper> --fast", "Test paper (fast mode)"),
                        row("deepcode mcp serve", "Expose DeepCode as an MCP server"),
                        row(
                            "deepcode service <command>",
                            "Manage the background service",
                        ),
                        row(
                            "deepcode serve --foreground",
                            "Run the service in this terminal",
                        ),
                        row("deepcode mcp <command>", "Connect and manage MCP tools"),
                        row(
                            "deepcode skill <command>",
                            "List, inspect, import, and manage Agent Skills",
                        ),
                        row(
                            "deepcode plugin <command>",
                            "Register and manage local Agent Plugins",
                        ),
                        row(
                            "deepcode provider <command>",
                            "Configure LLM connections and models",
                        ),
                        row(
                            "deepcode session delete <id>",
                            "Permanently delete a conversation Session",
                        ),
                        row(
                            "deepcode exec <task>",
                            "Run one headless coding task",
                        ),
                        row(
                            "deepcode loop <goal>",
                            "Run a durable Goal on the shared Turn runtime",
                        ),
                        row(
                            "deepcode loop --resume <session-id>",
                            "Continue the same durable Goal and Session",
                        ),
                        row(
                            "deepcode schedule ...",
                            "Run loop or memory maintenance on a schedule",
                        ),
                        row(
                            "deepcode automation <command>",
                            "Manage durable Agent Automations",
                        ),
                        "",
                        "Examples:",
                        row("deepcode --trust", "Start in a project you trust"),
                        row("deepcode --resume <session-id>", "Continue a saved conversation"),
                        row("deepcode provider list", "Show model connections"),
                        row("deepcode service status", "Check the background service"),
                        row("deepcode test rice", "Test RICE paper reproduction"),
                        row("deepcode test rice --fast", "Test RICE paper (fast mode)"),
                        "",
                        "Run 'deepcode <command> --help' for command options.",
                        "Run 'deepcode chat --help' for TUI options.",
                        "",
                        "Available papers:",
                    ]
                )
            )

            # List available papers
            papers_dir = "papers"
            if os.path.exists(papers_dir):
                for item in os.listdir(papers_dir):
                    item_path = os.path.join(papers_dir, item)
                    if os.path.isdir(item_path):
                        paper_md = os.path.join(item_path, "paper.md")
                        addendum_md = os.path.join(item_path, "addendum.md")
                        status = "ok" if os.path.exists(paper_md) else "--"
                        addendum = " (+addendum)" if os.path.exists(addendum_md) else ""
                        print(f"   [{status}] {item}{addendum}")
            print(
                "\n   Legend: [ok] = paper.md exists, (+addendum) = addendum.md exists"
            )
            return
        elif sys.argv[1].startswith("-"):
            # Agent flags belong to the default interactive surface, so
            # `deepcode -c team -m model` behaves exactly like
            # `python -m cli.tui -c team -m model`.
            from cli.tui.app import main as tui_main

            raise SystemExit(tui_main(sys.argv[1:]))
        else:
            # Unknown argument — show help hint
            print(f"Unknown option: {sys.argv[1]}")
            print("Run 'deepcode --help' for usage information.")
            sys.exit(1)
    else:
        # Default (no arguments) -> interactive coding agent (multi-turn TUI).
        from cli.tui.app import main as tui_main

        raise SystemExit(tui_main())


if __name__ == "__main__":
    main()
